AllCops:
  TargetRubyVersion: 2.5
  StyleGuideCopsOnly: true

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Enabled: false

Style/Alias:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: trailing

Style/SignalException:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/TrivialAccessors:
  ExactNameMatch: true

# See https://github.com/bbatsov/rubocop/issues/4637
SpaceAroundOperators:
  Enabled: false
